spring:
  output:
    ansi:
      enabled: ALWAYS

  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    url: jdbc:h2:mem:test

  config:
    use-legacy-processing: true

  jpa:
    hibernate:
      ddl-auto: create  # (1) ??? ?? ??
    show-sql: true      # (2) SQL ?? ??
    use_sql_comments: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        color-codes: true

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace